---
# This is a sample settings file. Feel free to add your own.
defaults: &defaults
  title: "PmpknPi"
  description: "A blog api"
  author: "Brock Whitten"
  password: "foobar"
  sanitizer: "None"

development:
  <<: *defaults
  domain: "http://localhost:4000"

test:
  <<: *defaults
  domain: "http://localhost:4000"
  
production:
  <<: *defaults
  domain: "http://demo.pmpknpi.com"